name: Auto Execution

on: [push]
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building the Docker image
      run: docker build -t autotx:latest .
      
    - name: Running the autoTx Script
      env: 
       YOUR_PUBLIC_KEY: ${{secrets.PK}}
       YOUR_HTTP_RPC_URL: ${{ secrets.GITHUB_TOKEN }}
      run: docker run --name="my-autotx" -e PK=$YOUR_PUBLIC_KEY -e HRPC=$YOUR_HTTP_RPC_URL autotx:latest
